---
- name: "install prometheus exporters on ubuntu"
  apt: name="{{item}}" state=present
  with_items:
    - prometheus-node-exporter
    - prometheus-blackbox-exporter
  become: yes

- name: "prometheus blackbox config file"
  copy: src=blackbox.yml dest=/etc/prometheus/blackbox.yml
  become: yes
