#!/usr/bin/env python
# 
# Script to
#
# Written by Dougal Scott <dougal.scott@gmail.com>

import os, sys, argparse

################################################################################
def Verbose(msg):
    if namespace.verbFlag:
    	sys.stderr.write("%s\n" % msg)

################################################################################
def Warn(msg):
    sys.stderr.write("Warning: %s\n" % msg)

################################################################################
def Fatal(msg):
    sys.stderr.write("Fatal: %s\n" % msg)
    sys.exit(255)

################################################################################
def parseArgs():
    global namespace
    parser=argparse.ArgumentParser()
    parser.add_argument('-v', '--verbose', dest='verbFlag', action='store_true', default=False)
    namespace=parser.parse_args()

################################################################################
def main():
    parseArgs()

################################################################################
if __name__=="__main__":
    main()

#EOF
