#!/bin/bash

os=`uname`

case $os in
    Darwin)
        sudo brew install git
        sudo brew install git-flow
        ;;
    Linux)
        sudo apt-get install git-core
        sudo apt-get install git-flow
        ;;
    *)
        echo "Unsupported os ${os}"
esac

#EOF
