#!/bin/bash

os=`uname`

case $os in
    Darwin)
        # Should already be installed by default
        # brew install zsh
        ;;
    Linux)
        sudo apt-get install zsh
        ;;
    *)
        echo "Unsupported os ${os}"
esac

cd $HOME
if [ ! -d antigen ]; then
    git clone https://github.com/zsh-users/antigen.git
fi

#EOF
