#!/bin/bash

os=`uname`

case $os in
    Darwin)
        brew install python
        sudo pip install virtualenv
        sudo pip install virtualenvwrapper
        ;;
    Linux)
        sudo apt-get install -y python2.7
        sudo apt-get install -y python-pip
        sudo apt-get install -y python-dev
        sudo apt-get install -y python-virtualenv
        sudo apt-get install -y virtualenvwrapper
        sudo pip install flake8
        ;;
    *)
        echo "Unsupported os ${os}"
esac

#EOF
