#!/bin/bash

os=`uname`

case $os in
    Darwin)
        sudo port install vim
        ;;
    Linux)
        sudo apt-get install vim
        ;;
    *)
        echo "Unsupported os ${os}"
esac
 
mkdir -p ~/.vim/autoload
curl -LSso ~/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim

mkdir -p ~/.vim/bundle
cd ~/.vim/bundle && git clone https://github.com/scrooloose/syntastic.git

#EOF
