#!/bin/bash

os=`uname`

case $os in
    Darwin)
        sudo port install zsh
        ;;
    Linux)
        sudo apt-get install zsh
        ;;
    *)
        echo "Unsupported os ${os}"
esac

git clone https://github.com/zsh-users/antigen.git

#EOF
