#!/bin/bash

os=`uname`

case $os in
    Darwin)
        sudo port install python27
        sudo port install py27-pip
        sudo port install py27-virtualenv
        sudo port install py27-virtualenvwrapper
        ;;
    Linux)
        sudo apt-get install python2.7
        sudo apt-get install python-pip
        sudo apt-get install python-virtualenv
        sudo apt-get install virtualenvwrapper
        ;;
    *)
        echo "Unsupported os ${os}"
esac

#EOF
