---
- name: "install git on macos"
  homebrew: name="{{item}}" state=installed
  with_items:
    - git
    - git-flow
    - pre-commit
  when: ansible_distribution == "MacOSX"

- name: "install git on ubuntu"
  apt: name="{{item}}" state=present
  with_items:
    - git-core
    - git-flow
  when: ansible_distribution == "Ubuntu"
  become: yes

- name: "install git on CentOS"
  yum: name="{{item}}" state=installed
  with_items:
    - git
    - gitflow
  when: ansible_distribution == "CentOS"
  become: yes

- name: "gitconfig configfile"
  copy: src=dot_gitconfig dest={{ansible_user_dir}}/.gitconfig

- name: "gitignore configfile"
  copy: src=dot_gitignore_global dest={{ansible_user_dir}}/.gitignore_global
