---
- include: git.yml
- include: zsh.yml
- include: vim.yml
- include: python.yml
- include: nethack.yml
- include: misc.yml
- include: mac.yml

- name: "Copy configdir"
  copy: src=dot_config dest={{ansible_user_dir}}/.config
