---
- include_tasks: git.yml
- include_tasks: zsh.yml
- include_tasks: vim.yml
- include_tasks: python.yml
- include_tasks: nethack.yml
- include_tasks: misc.yml
- include_tasks: mac.yml

- name: "Copy configdir"
  copy: src=dot_config dest={{ansible_user_dir}}/.config
