---
- name: "install wireshark_chmod on macos"
  homebrew: name=wireshark-chmodbpf
  when: ansible_distribution == "MacOSX"

- name: "install wireshark on macos"
  homebrew: name=wireshark
  when: ansible_distribution == "MacOSX"

- name: "install wget on macos"
  homebrew: name=wget state=installed
  when: ansible_distribution == "MacOSX"

- name: "ssh dir"
  file: path={{anisble_user_dir}/.ssh state=directory

- name: "ssh config"
  copy: src=ssh_config dest={{ansible_user_dir}}/.ssh/config
