---
- name: "install python on macos"
  homebrew: name={{item}} state=installed
  with_items:
    - python
    - python3
  when: ansible_distribution == "MacOSX"

- name: "install python on ubuntu"
  apt: name={{item}} state=installed
  with_items:
    - python
    - python-pip
    - python-virtualenv
    - virtualenvwrapper
    - python3
    - python3-pip
  when: ansible_distribution == "Ubuntu"
