---
- name: "install python3 on macos"
  homebrew: name={{item}} state=installed
  with_items:
    - python3
    - black
    - flake8
    - pylint
    - cookiecutter
  when: ansible_distribution == "MacOSX"

- name: "install python on ubuntu"
  apt: name={{item}} state=installed
  with_items:
    - python
    - python-pip
    - python-virtualenv
    - virtualenvwrapper
    - python3
    - python3-pip
  when: ansible_distribution == "Ubuntu"
  become: yes

- name: "install python on CentOS"
  yum: name={{item}} state=installed
  with_items:
    - python
    - python-pip
    - python-virtualenv
    - python-virtualenvwrapper
    - python34
  when: ansible_distribution == "CentOS"
  become: yes

- name: "Config directory"
  file: path={{ansible_user_dir}}/.config state=directory

- name: "flake8 config"
  copy: src=flake8 dest={{ansible_user_dir}}/.config/flake8
