---
- name: "install python on macos"
  homebrew: name={{item}} state=installed
  with_items:
    - python
  when: ansible_distribution == "MacOSX"

- name: "install python3 on macos"
  homebrew: name={{item}} state=installed
  with_items:
    - python3
  when: ansible_distribution == "MacOSX"

- name: "install virtualenvwrapper on MacOSX"
  pip: name=virtualenvwrapper
  when: ansible_distribution == "MacOSX"

- name: "install python on ubuntu"
  apt: name={{item}} state=installed
  with_items:
    - python
    - python-pip
    - python-virtualenv
    - virtualenvwrapper
  when: ansible_distribution == "Ubuntu"
  become: yes

- name: "install python3 on ubuntu"
  apt: name={{item}} state=installed
  with_items:
    - python3
    - python3-pip
  when: ansible_distribution == "Ubuntu"
  become: yes
