---
- name: "install vim on macos"
  homebrew: name=vim state=installed
  when: ansible_distribution == "MacOSX"

- name: "install vim on CentOS"
  yum: name=vim state=installed
  when: ansible_distribution == "CentOS"
  become: yes

- name: "install vim on ubuntu"
  apt: name=vim state=present
  when: ansible_distribution == "Ubuntu"
  become: yes

- name: "vimrc configfile"
  copy: src=dot_vimrc dest={{ansible_user_dir}}/.vimrc

- name: "vim configdir"
  copy: src=dot_vim dest={{ansible_user_dir}}/.vim

- name: install vim autoload dir
  file:
      path: "{{ansible_user_dir}}/.vim/autoload"
      state: directory

- name: install vim bundle dir
  file:
    path: "{{ansible_user_dir}}/.vim/bundle"
    state: directory

- name: install pathogen
  get_url:
    url: https://tpo.pe/pathogen.vim
    dest: "{{ansible_user_dir}}/.vim/autoload/pathogen.vim"

- name: install black
  git:
    repo=https://github.com/ambv/black.git
    dest={{ansible_user_dir}}/.vim/bundle/black

- name: install antigen
  git:
    repo=https://github.com/vim-syntastic/syntastic.git
    dest={{ansible_user_dir}}/.vim/bundle/syntastic

- name: install terraform
  git:
    repo=https://github.com/hashivim/vim-terraform.git
    dest={{ansible_user_dir}}/.vim/bundle/vim-terraform
