---
- name: "install zsh on macos"
  homebrew: name=zsh state=installed
  when: ansible_distribution == "MacOSX"

- name: "install zsh on ubuntu"
  apt: name=zsh state=installed
  when: ansible_distribution == "Ubuntu"
  become: yes

- name: "install zsh on CentOS"
  yum: name=zsh state=installed
  when: ansible_distribution == "CentOS"
  become: yes

- name: configure zsh
  copy: src=dot_zshrc dest={{ansible_user_dir}}/.zshrc

- name: install antigen
  git: 
    repo=https://github.com/zsh-users/antigen.git
    dest={{ansible_user_dir}}/antigen
    force=yes

