route:
  receiver: 'mail'
  repeat_interval: 24h
  group_by: [ alertname ]


receivers:
  - name: 'mail'
    email_configs:
      - smarthost: 'smtp.gmail.com:465'
        auth_username: 'dougal.scott@gmail.com'
        auth_password: ""
        from: 'dougal.scott@gmail.com'
        to: 'dougal.scott@gmail.com'
