---

- name: "install nfs client"
  apt: name="{{item}}" state=present
  with_items:
    - nfs-common
  become: true

- name: Create /backup directory
  ansible.builtin.file:
    path: /Backups
    state: directory
    mode: '0755'
  become: true
  ignore_errors: true

- name: Mount an NFS volume
  ansible.posix.mount:
    src: windyarm.local:/volume1/Backups
    path: /Backups
    state: mounted
    fstype: nfs
  become: true

- name: "install mediawiki backup script"
  copy:
    src: backup_mediawiki
    dest: /usr/local/bin/.
    mode: '0755'
    owner: root
    group: root
  become: true

- name: Backup mediawiki
  cron:
    name: "mediawiki backup"
    special_time: daily
    job: "/usr/local/bin/backup_mediawiki"
  become: true

- name: Create /Backups/calibre directory
  ansible.builtin.file:
    path: /Backups/calibre
    state: directory
    mode: '0755'
  become: true
  ignore_errors: true

- name: "install calibre backup script"
  copy:
    src: backup_calibre
    dest: /usr/local/bin/.
    mode: '0755'
    owner: root
    group: root
  become: true

- name: Backup calibre
  cron:
    name: "calibre backup"
    special_time: daily
    job: "/usr/local/bin/backup_calibre"
  become: true
