---
- name: "include vars"
  include_vars:
    dir: "vars"

- name: "prometheus config file"
  copy: src=prometheus.yml dest=/etc/prometheus/prometheus.yml
  become: true

- name: "alertmanger config file"
  template:
    src=alertmanager.yml.j2
    dest=/etc/prometheus/alertmanager.yml
  become: true
