#!/usr/local/bin/python
# 
# Script to check XXX
#
# Written by Dougal Scott <dougal.scott@tollgroup.com>
# $Id$
# $HeadURL$

import os
import sys
import optparse
from toll import graph, check

graphFlag=True

################################################################################
def main():
    parser=optparse.OptionParser()
    parser.add_option('--nograph', dest='graphFlag', action='store_false', default=True)
    (opts,args)=parser.parse_args()

    check.exitOk("No problems encountered")

################################################################################
if __name__=="__main__":
    main()

#EOF
