#!/usr/bin/env python
#
# Script to
#
# Written by Dougal Scott <dougal.scott@gmail.com>

import sys
import argparse

verbFlag = False


################################################################################
def verbose(msg):
    if verbFlag:
        sys.stderr.write("%s\n" % msg)


################################################################################
def warn(msg):
    sys.stderr.write("Warning: %s\n" % msg)


################################################################################
def fatal(msg):
    sys.stderr.write("Fatal: %s\n" % msg)
    sys.exit(255)


################################################################################
def parse_args():
    global verbFlag
    parser = argparse.ArgumentParser()
    parser.add_argument('-v', '--verbose', dest='verbFlag', action='store_true', default=False)
    args = parser.parse_args()
    verbFlag = args.verbFlag
    return args


################################################################################
def main():
    args = parse_args()


################################################################################
if __name__ == "__main__":
    main()

# EOF
